# Jekyll configuration to exclude node_modules
exclude:
  - node_modules
  - project-management-app/backend/node_modules
  - project-management-app/frontend/node_modules
  - project-management-app/cloudrun/node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .git
  - DEVELOPMENT.md